### ISSUE TITLE
Querverweis auf die Internetseite ist fehlerhaft

### ISSUE THREAD

**Issue by BasicMan01** [irgendsontyp/lange-nacht-der-wissenschaften-chooser#1]
Der Link, welcher direkt auf die Internetseite führt, funktioniert nicht.

Beispiel:
http://www.nacht-der-wissenschaften.dehttp//www.nacht-der-wissenschaften.de/2017/programm/nach-touren/detailansicht-veranstalter/campus-m21-fom-hochschule-nuernberg/fom-hochschule-nuernberg-1/

Hier wird die Domaine doppelt aufgeführt. Man muss den überflüssigen Bereich erst entfernen, damit der Link funktioniert.

**Comment by irgendsontyp** [comment]
Ach ja? Wie wäre es, wenn ich dir mal schön einen Zahn ohne Betäubung ziehen würde? Vielleicht bist du dann nicht mehr so frech!

Ääääh ich meine: Vielen Dank für den Report. Ich hab das nicht bemerkt, weil ich die URL gar nicht mehr geprüft habe. Bevor ich das Projekt auf GitHub gepusht hab, ging das mit der URL noch. Ich hab dann noch ein paar Sachen verbessert, weil man vorher nacheinander Funktionen aus- und einkommentieren musste, um den Datenbestand zu füllen. Im Zuge dieser Arbeiten hab ich auch die Stelle mit der URL angepasst und dabei ging das futsch.

**Comment by BasicMan01** [comment]
Funktioniert

**Comment by BasicMan01** [comment]
Heute Volleyball, nur dass das klar ist.

Hab den issue geschlossen.Durfte ich das?

Am 04.10.2017 16:31 schrieb "irgendsontyp" <notifications@github.com>:

**Comment by irgendsontyp** [comment]
> Hab den issue geschlossen.Durfte ich das?

Ja, das war gut. Danke!
